// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIj5Kx1adeuShWP6B-bHIlXeNOEthVs9s',
    appId: '1:957944593804:web:210d2fb25f2954f3eceaa9',
    messagingSenderId: '957944593804',
    projectId: 'advance-airline-413323',
    authDomain: 'advance-airline-413323.firebaseapp.com',
    storageBucket: 'advance-airline-413323.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZIIHxhIoh6M3LxBiKSJC8M9HrZL9hISQ',
    appId: '1:957944593804:android:31d1c42906c51ddaeceaa9',
    messagingSenderId: '957944593804',
    projectId: 'advance-airline-413323',
    storageBucket: 'advance-airline-413323.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZSCp6LsqtC2joHe41b6KG8v1Tae9PmTc',
    appId: '1:957944593804:ios:30c087f7f662bf9beceaa9',
    messagingSenderId: '957944593804',
    projectId: 'advance-airline-413323',
    storageBucket: 'advance-airline-413323.appspot.com',
    iosBundleId: 'com.example.appnote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZSCp6LsqtC2joHe41b6KG8v1Tae9PmTc',
    appId: '1:957944593804:ios:128096c3d354c42aeceaa9',
    messagingSenderId: '957944593804',
    projectId: 'advance-airline-413323',
    storageBucket: 'advance-airline-413323.appspot.com',
    iosBundleId: 'com.example.appnote.RunnerTests',
  );
}
